### ISSUE TITLE
Leistungszertifikate

### ISSUE THREAD

**Issue by annalenahansen** [eduhub-org/eduhub#1101]
**Describe the bug**
After clicking 'Leistungszertifikate' ausstellen, not all certificates are created, even after multiple tries. 

**To Reproduce**
1. Go to https://edu.opencampus.sh/manage/course/479
2. Click on 'Leistungszertifikate ausstellen'
3. Scroll down to 'Kadisatou Fane'
4. See error: No certificate

**Expected behavior**
A certificate for all participants should be created

**Environment (please complete the following information):**

 - Browser [firefox]

**Comment by ericstumper** [comment]
I can see a lot of flask errors in the cloud run function logs, but I can't make sense of them and I don't know much python to know where to look:

```
Exception on / [POST]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'run' did not return a valid response. The function either returned None or ended without a return statement.
```

Can you make sense of this @steffen74 ?
